[project]
name = "Enterprise-Vibe-Coding"
version = "1.0.0"
description = "A programming language compiled using *Vibes*."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]
